[build]
builder = "DOCKERFILE"
dockerfilePath = "apps/api/Dockerfile"
watchPatterns = ["apps/api/**", "packages/**"]

[deploy]
healthcheckPath = "/v2/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
